version: '3'
services:
    app:
        volumes:
            - ${PWD}:~/dev/projects/LOL101
        container_name: riot
        restart: always
        build: .
        ports:
            - '3000:3000'